### ISSUE TITLE
[Android] Messages disappear after they're sent

### ISSUE THREAD

**Issue by zingmars** [zulip/zulip-mobile#2413]
When I send a private message they don't appear at the bottom of the conversation view and there is no way to forcefully refresh this view. In fact, there doesn't seem to be a way to forcefully refresh anything, which was a bit annoying when I had to restart the app to get a reactivated user to show up in the users view.

Video of the messages disappearing: https://youtu.be/n1sIXJQYqRc

Using Android 8.0 on a OnePlus 3. App version v12.4.84.

**Comment by pulkonet** [comment]
Are you sure you're on the latest version? This bug was fixed in this version update via [08d1df](https://github.com/zulip/zulip-mobile/commit/08d1df541a48df9bc739e4ba93472e982b9c08f4) and I was also unable to reproduce this using the same environment.

**Comment by zingmars** [comment]
Yup. Reinstalled from github to test. Issue still happens.

**Comment by borisyankov** [comment]
Thanks for reporting this. I will test very thoroughly, though the issue you are reporting was fixed by the exact commit @pulkonet is mentioning.

**Comment by Yoshi8765** [comment]
I still get a form of this in my android version (also similar to #2287). My current version is v12.4.84 . 
I just started talking to a user on mobile via PM, and every single message I wrote would not show up. only when they respond, and I click the notification that comes up, will my sent messages (along with their new message) show up.
This user isn't someone I just started talking to, there's already past message history.
It's been happening with basically every PM I send.
I tried to fully close the app by tapping my recents button, and swiping left/right on zulip to close it, and reopen. It didn't work.

**Comment by Yoshi8765** [comment]
strangely enough, no issue when I sent a PM to a different person. https://streamable.com/zoqyd

**Comment by borisyankov** [comment]
@Yoshi8765 I think I know one case where this will be happening and will be fixing it next.
Hope it is only this single case needed fixing.

**Comment by borisyankov** [comment]
@Yoshi8765 I did test extensively and what I expected might be the cause is working. So I am not sure how to reproduce.

The red bug you are getting might be something related to message encoding (a wild educated guess) but I have no idea what is going on.

**Comment by Yoshi8765** [comment]
@borisyankov ok, if that's the case I'll closely watch the app and try to report with as much info as possible if it happens again.

**Comment by borisyankov** [comment]
Thanks. 👍 
I hope it never appears, but if it does and we can reproduce, this will be a very high priority fix.

**Comment by sschueller** [comment]
I have this issue on 18.0.99. Messages I write only appear after I go out of the chat and back in. It happens every time. Server is a zulipchat.com instance.
