### ISSUE TITLE
iOS app crashes inside RN with invalid UTF-16 in JSON

### ISSUE THREAD

**Issue by mikeslywka** [zulip/zulip-mobile#3498]
I see this has been an issue in the past but this is happening for us now as well since this morning I've started getting reports from our users that the IOS app completely crashes when going to the private messages tab.
I was able to reproduce.
Tried uninstalling and re-installing.
App version 23.2.111
zulip server version is on master branch (2.0.3 I think)

Mike

**Comment by borisyankov** [comment]
I was not able to reproduce.

**Comment by borisyankov** [comment]
@mikeslywka I noticed an error reported in our error log system that might be related to your issue.
Can you confirm if the realm that you are connecting is at `https://chat.w***s.com`? (the *** are for privacy)

**Comment by mikeslywka** [comment]
Yes that is the correct realm that we are connecting to! Thanks for looking into it!

**Comment by borisyankov** [comment]
@gnprice Just linked the Sentry issue with more information.

@ishammahajan if you do not have access to our Sentry error reports, maybe it is now time to add you.
These are a good source of issues to work on.

**Comment by gnprice** [comment]
Copying here relevant details from the Sentry event:

Here's the exception text:
```
Error: C++ exception in 'nativeFlushQueueImmediate'

json parse error on line 0 near `VM"}]],2563]': expected another unicode escape for second half of surrogate pair

This error is located at:
    in RCTText
    in H
    in Text
    [... long inscrutable stack as usual ...]
```

Then Sentry provides some kind of interpretation of the stack as
> app:///[native code] in nativeFlushQueueImmediate
> node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js in enqueueNativeCall at line 254:14
> node_modules/react-native/Libraries/BatchedBridge/NativeModules.js in createView at line 127:21
> node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js in completeUnitOfWork at line 5210:27
> [... a bunch more frames in the same "renderer" file, then boring others ...]

I think the key bits are:
* RN is sending some data over [the bridge](https://tadeuzagallo.com/blog/react-native-bridge/) from JS to native code.
* That data is JSON -- that's probably how it always works.
* The JSON doesn't actually parse. :-/ Seems like this is a bug in RN, whatever else it is -- it made some JSON on one side that it rejects as ill-formed on the other.
* The explanation for why it doesn't parse is "expected another unicode escape for second half of surrogate pair".

**Comment by gnprice** [comment]
Further thoughts:
* See background on surrogate pairs here: https://unicodebook.readthedocs.io/unicode_encodings.html#utf-16-surrogate-pairs or here: https://en.wikipedia.org/wiki/UTF-16
* Other perhaps-relevant background: JS "strings" are really sequences of UTF-16 code units -- it's possible for them to be invalid UTF-16, which means to have bad use of surrogates.
  * And I'd guess the same is true of JSON.
* So one thing that might be happening is:
  * We have some data for some reason that contains a string which has an unpaired surrogate, i.e. is not valid UTF-16.
  * On the PMs screen, that data becomes a prop of a native view, or something, causing it to be sent over the bridge.
  * The JS side of the bridge cheerfully encodes that data "as JSON", producing invalid JSON.
  * The native side tries to decode it and rejects it because it's invalid.

For working on this bug, I think the next steps are:
* Play with valid and invalid UTF-16 in JSON, to understand what's valid and invalid.
  * (First, read the background linked above.)
  * Here's a quick demo:
```
$ echo '"\ud83d\ude03"' | jq .
"😃"

$ echo '"\ud83d"' | jq .
parse error: Invalid \uXXXX\uXXXX surrogate pair escape at line 1, column 8
```
* Reproduce the issue in our app. Try sticking invalid UTF-16 in a user's name, or something. (Please don't do this on chat.zulip.org, to avoid triggering the bug for other people -- use a test realm, e.g. on zulipchat.com.)
* Look for reports of the bug in the RN tracker.
* If it's not there already, report it; if it is, see if you can contribute with a clearer repro, or clearer explanation.
* In particular, try reproducing in a tiny RN app.

**Comment by chrisbobbe** [comment]
From Sentry, it looks like the latest occurrence of this was on November 28th; is it possible that this has been resolved?

**Comment by chrisbobbe** [comment]
> From Sentry, it looks like the latest occurrence of this was on November 28th; is it possible that this has been resolved @gnprice ?

No, it seems like this is still happening! https://sentry.io/organizations/zulip/events/?project=191284&query=nativeFlushQueueImmediate&statsPeriod=90d

**Comment by ray-kraesig** [comment]
We're still getting events, but [the event metadata](https://sentry.io/organizations/zulip/eventsv2/results/?field=title&field=release&field=timestamp&id=1600&name=Issue+%233498%20%28modified%29&project=191284&query=nativeFlushQueueImmediate&sort=-timestamp&statsPeriod=90d&widths=431&widths=194&widths=-1) shows it's *only* happening on iOS version 23.2.111. The issue metadata is perhaps less reliable here, as it's dependent on Sentry's bucketing algorithm, but it indicates there have *never* been occurrences of this bug on any other release, before or since.

The following iOS release was the one where [we switched to a different WebView implementation](https://github.com/zulip/zulip-mobile/blob/13c136154f19e88688dba3edb10bed50b9c26ad4/docs/changelog.md#full-changes-for-users), which in conjunction with Greg's analysis above gives a very plausible cause for it vanishing.

Deprioritizing, closing, and (in Sentry) marking the issue "resolved as of v113" – which, IIUC, should reopen it there if it ever occurs in any later release.

**Comment by mikeslywka** [comment]
I had a report of this happening again this morning for a user running iOS 13.3  which I believe is the current iOS version. I'm not sure where you are getting the 23.2.111 version from.
I will see if updating the version of zulip that I am running helps but I wanted to let you know that people are still getting this error and I don't think this issue should be closed.
Thanks

**Comment by chrisbobbe** [comment]
@mikeslywka, thanks for this report; we certainly don't want to close an issue prematurely!

I see how this could be confusing — it looks like Ray meant that the logs show that it's only happening on iOS, as opposed to Android (irrespective of the iOS version), and only for users on the [23.2.111 release of the Zulip mobile app](https://github.com/zulip/zulip-mobile/releases/tag/23.2.111).

If you haven't upgraded already, it would be helpful to know if you're on that release, which you can find out by tapping the gear icon at the bottom, then Diagnostics. I suspect that if you upgrade Zulip to the latest release, you'll no longer see this crash, but please do let us know if it's still happening there, and we'll re-open this. 🙂

**Comment by mikeslywka** [comment]
Looks like I am on v26.17.140 according to the mobile application (Gear at
bottom, then Diagnostics) - on the server itself the contents
of /home/zulip/deployments/current/version.py however says ZULIP_VERSION =
"2.0.3+git"
So just to be clear, we are talking about upgrading the version of the
zulip server software I'm running correct?
Thanks for your help with this!
Mike

**Comment by chrisbobbe** [comment]
Hi Mike,

No, you shouldn't have to upgrade the Zulip server software to address this issue. I'm still only seeing Sentry logs of this particular error ("expected another unicode escape for second half of surrogate pair") for users on v23.2.111 of the mobile app.

For each user who reports this crash, have you tried upgrading the Zulip mobile app on their device to the latest version? If crashes are still happening after that, it's possible that it has a different cause, which we should track in a new issue, or bump the priority of an existing issue that covers it ([here](https://github.com/zulip/zulip-mobile/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22severe%3A+crash%22+) are our open issues addressing crashes), if there is one. Is it still the case that the app crashes every single time your users visit the private messages tab, or is it only affecting some users, or some users part of the time, etc.?

**Comment by mikeslywka** [comment]
Just wanted to provide an update here. The affected user upgraded their
zulip mobile app and that indeed fixed the issue with the app crashing on
direct messages.
Thanks for everyone’s help with this.

Mike

**Comment by chrisbobbe** [comment]
Thanks, Mike! 🙂
